In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(('/Users/kimzoldak/Github/GRB_Hubble_Diagram/data/'
                    'Band_13_GBM+LAT__22_GBMconstrained.txt'), 
                   sep='\t')

cols2keep = ['eiso', 'eiso_err_low', 'eiso_err_up', 
             'epeakRest', 'epeakRest_err_low', 'epeakRest_err_up']

df = data.loc[:, cols2keep]

In [3]:
df.head(10)

,eiso,eiso_err_low,eiso_err_up,epeakRest,epeakRest_err_low,epeakRest_err_up
0,3.482210e+54,7.055090e+52,7.055090e+52,2731.929350,183.746653,183.746653
1,4.101983e+54,9.066845e+52,9.066845e+52,3209.456160,243.199227,243.199227
2,1.181308e+53,3.397760e+51,3.397760e+51,1102.755808,89.911198,89.911198
3,2.788213e+52,1.939489e+51,1.939489e+51,3905.486937,630.013379,630.013379
4,3.380852e+54,2.624849e+52,2.624849e+52,2880.751218,51.922253,51.922253
5,1.976261e+54,1.059907e+52,1.059907e+52,940.280908,12.310902,12.310902
6,9.028069e+52,2.585904e+51,2.585904e+51,735.337079,44.470956,44.470956
7,2.385640e+52,2.505833e+51,2.505833e+51,215.132038,36.475764,36.475764
8,9.033835e+53,2.998544e+52,2.998544e+52,765.163659,25.028600,25.028600
9,6.049283e+53,1.005963e+52,1.005963e+52,982.410320,53.816136,53.816136

In [4]:
df.tail(10)

,eiso,eiso_err_low,eiso_err_up,epeakRest,epeakRest_err_low,epeakRest_err_up
25,8.699091e+52,5.024620e+51,5.024620e+51,129.110606,15.062264,23.850957
26,2.471171e+52,2.120992e+51,2.120992e+51,60.869801,6.034001,5.517176
27,3.565032e+53,1.510157e+52,1.510157e+52,558.253310,21.800231,23.997792
28,3.561701e+52,2.183825e+51,2.183825e+51,121.734858,20.986473,19.628214
29,1.830322e+54,2.410556e+52,2.410556e+52,2930.836175,79.663865,81.827542
30,1.940275e+53,2.031602e+52,2.031602e+52,876.077519,140.413975,203.169477
31,1.246552e+53,6.356509e+51,6.356509e+51,212.576586,21.070886,18.146118
32,2.827733e+52,7.911024e+50,7.911024e+50,114.881089,3.847313,4.046673
33,3.122605e+53,1.426054e+52,1.426054e+52,466.707681,25.528114,25.838021
34,9.646100e+52,2.661216e+51,2.661216e+51,200.049248,7.701302,7.889839

In [5]:
from logdata import *

In [6]:
param = 'epeakRest'
out = to_log(  x = df[param], 
               xerr=[df[param+'_err_low'], 
                     df[param+'_err_up']], 
               which='both', 
               errTypeReturn='ci'
            )

out

You have Margins of Error

(array([3.43646946, 3.50643145, 3.04247935, 3.59167519, 3.45950575,
        2.97325762, 2.86648647, 2.33270509, 2.88375434, 2.99229292,
        3.16820682, 3.05053867, 2.55857095, 2.85059   , 2.457404  ,
        2.79032391, 2.40343558, 2.43401211, 2.27210394, 1.74770618,
        2.3255078 , 2.53830136, 2.42366128, 2.38899218, 2.43898041,
        2.11096192, 1.78440188, 2.74683131, 2.08541495, 3.46699154,
        2.94254254, 2.32751543, 2.06024854, 2.66904495, 2.30113692]),
 array([3.40623056, 3.47220877, 3.00554282, 3.5152741 , 3.45160669,
        2.96753394, 2.8393939 , 2.25201827, 2.86931098, 2.96782596,
        3.15276556, 3.02757416, 2.55182023, 2.78560252, 2.45069745,
        2.76245284, 2.39265631, 2.42497384, 2.25419078, 1.72281051,
        2.27674394, 2.4910289 , 2.36810024, 2.36968447, 2.3244098 ,
        2.05708898, 1.73906419, 2.72953174, 2.00323809, 3.45502346,
        2.86667924, 2.2821817 , 2.04545511, 2.64461539, 2.28408755]),
 array([3.46473926, 3.53815323, 3.07651921, 3.6566252 , 3.46726371,
        2.97890684, 2.89198771, 2.4007241 , 2.89773277, 3.01545468,
        3.18311787, 3.07234961, 2.56521834, 2.9167639 , 2.46449556,
        2.82036227, 2.41356905, 2.4431272 , 2.28947212, 1.77189853,
        2.36724987, 2.6025637 , 2.48289077, 2.40858534, 2.50304234,
        2.18458231, 1.82208289, 2.76511032, 2.15033597, 3.47895066,
        3.03312085, 2.36309033, 2.07528325, 2.69244653, 2.31793613]))

In [7]:
param = 'epeakRest'
out = to_log(  x = df[param], 
               xerr=[df[param+'_err_low'], 
                     df[param+'_err_up']], 
               which='both', 
               errTypeReturn='moe'
            )

out

You have Margins of Error

(array([3.43646946, 3.50643145, 3.04247935, 3.59167519, 3.45950575,
        2.97325762, 2.86648647, 2.33270509, 2.88375434, 2.99229292,
        3.16820682, 3.05053867, 2.55857095, 2.85059   , 2.457404  ,
        2.79032391, 2.40343558, 2.43401211, 2.27210394, 1.74770618,
        2.3255078 , 2.53830136, 2.42366128, 2.38899218, 2.43898041,
        2.11096192, 1.78440188, 2.74683131, 2.08541495, 3.46699154,
        2.94254254, 2.32751543, 2.06024854, 2.66904495, 2.30113692]),
 array([0.0302389 , 0.03422268, 0.03693653, 0.07640109, 0.00789906,
        0.00572368, 0.02709257, 0.08068682, 0.01444336, 0.02446696,
        0.01544126, 0.02296451, 0.00675072, 0.06498747, 0.00670655,
        0.02787107, 0.01077927, 0.00903827, 0.01791316, 0.02489568,
        0.04876386, 0.04727246, 0.05556103, 0.01930771, 0.11457061,
        0.05387294, 0.0453377 , 0.01729956, 0.08217686, 0.01196808,
        0.0758633 , 0.04533372, 0.01479344, 0.02442956, 0.01704937]),
 array([0.0282698 , 0.03172179, 0.03403985, 0.06495001, 0.00775796,
        0.00564923, 0.02550124, 0.06801901, 0.01397844, 0.02316176,
        0.01491105, 0.02181094, 0.00664739, 0.0661739 , 0.00709156,
        0.03003836, 0.01013347, 0.00911509, 0.01736818, 0.02419235,
        0.04174207, 0.06426234, 0.05922949, 0.01959317, 0.06406193,
        0.07362039, 0.03768101, 0.01827901, 0.06492102, 0.01195911,
        0.09057831, 0.03557491, 0.0150347 , 0.02340159, 0.01679921]))

In [8]:
param = 'epeakRest'
out = to_log(  x = df[param], 
               xerr=[df[param+'_err_low'], 
                     df[param+'_err_up']], 
               which='average', 
               errTypeReturn='moe'
            )

out

You have Margins of Error

(array([3.43646946, 3.50643145, 3.04247935, 3.59167519, 3.45950575,
        2.97325762, 2.86648647, 2.33270509, 2.88375434, 2.99229292,
        3.16820682, 3.05053867, 2.55857095, 2.85059   , 2.457404  ,
        2.79032391, 2.40343558, 2.43401211, 2.27210394, 1.74770618,
        2.3255078 , 2.53830136, 2.42366128, 2.38899218, 2.43898041,
        2.11096192, 1.78440188, 2.74683131, 2.08541495, 3.46699154,
        2.94254254, 2.32751543, 2.06024854, 2.66904495, 2.30113692]),
 array([0.02925435, 0.03297223, 0.03548819, 0.07067555, 0.00782851,
        0.00568645, 0.0262969 , 0.07435292, 0.0142109 , 0.02381436,
        0.01517615, 0.02238772, 0.00669906, 0.06558069, 0.00689906,
        0.02895472, 0.01045637, 0.00907668, 0.01764067, 0.02454401,
        0.04525297, 0.0557674 , 0.05739526, 0.01945044, 0.08931627,
        0.06374667, 0.04150935, 0.01778929, 0.07354894, 0.0119636 ,
        0.08322081, 0.04045431, 0.01491407, 0.02391557, 0.01692429]))

```


```
### Eiso errors are symmetric, so if we use only the lower error and ask for lower and upper errors, you should get consistent answers with had you used both the lower and upper errors.

In [9]:
param = 'eiso'
out1 = to_log(  x = df[param], 
               xerr=[df[param+'_err_low'], 
                     df[param+'_err_up']], 
               which='both', 
               errTypeReturn='ci'
            )

out1

You have Margins of Error

(array([54.54185491, 54.61299381, 53.07236324, 52.44532602, 54.52902616,
        54.29584438, 52.95559486, 52.377605  , 53.95587216, 53.7817039 ,
        54.22798906, 53.77951585, 53.27529528, 53.50577426, 53.5529516 ,
        53.37900051, 52.6214454 , 53.38880257, 52.59277242, 52.16047497,
        52.80329796, 52.60744442, 53.10608739, 51.88501589, 53.41045805,
        52.93947386, 52.39290272, 53.55206348, 52.55165741, 54.26252752,
        53.28786324, 53.09571032, 52.45143842, 53.49451712, 52.98435176]),
 array([54.53296558, 54.60328668, 53.0596886 , 52.41401427, 54.52564119,
        54.2935089 , 52.94297377, 52.32940952, 53.94121223, 53.7744211 ,
        54.22098992, 53.77238061, 53.27141232, 53.47471939, 53.54521102,
        53.35218583, 52.61123855, 53.3820609 , 52.56605542, 52.15291142,
        52.76868486, 52.52090812, 53.0514135 , 51.85027676, 53.37507535,
        52.91363527, 52.35392996, 53.53326564, 52.5241777 , 54.25676981,
        53.23982845, 53.07297985, 52.43911516, 53.47421627, 52.97220184]),
 array([54.55056593, 54.62248872, 53.08467844, 52.47453128, 54.53238494,
        54.29816736, 52.96785951, 52.42098227, 53.97005335, 53.78886659,
        54.23487718, 53.78653576, 53.27914384, 53.53475593, 53.56055664,
        53.40425541, 52.63141786, 53.39544117, 52.61794066, 52.16790905,
        52.83535488, 52.67956959, 53.15464155, 51.91718088, 53.44317397,
        52.96386112, 52.42866433, 53.57008133, 52.57750135, 54.26820989,
        53.33111032, 53.11731003, 52.46342163, 53.51391124, 52.996171  ]))

In [10]:
param = 'eiso'
out2 = to_log(  x = df[param], 
               xerr = df[param+'_err_low'], 
               which='both', 
               errTypeReturn='ci'
            )

out2

(array([54.54185491, 54.61299381, 53.07236324, 52.44532602, 54.52902616,
        54.29584438, 52.95559486, 52.377605  , 53.95587216, 53.7817039 ,
        54.22798906, 53.77951585, 53.27529528, 53.50577426, 53.5529516 ,
        53.37900051, 52.6214454 , 53.38880257, 52.59277242, 52.16047497,
        52.80329796, 52.60744442, 53.10608739, 51.88501589, 53.41045805,
        52.93947386, 52.39290272, 53.55206348, 52.55165741, 54.26252752,
        53.28786324, 53.09571032, 52.45143842, 53.49451712, 52.98435176]),
 array([54.53296558, 54.60328668, 53.0596886 , 52.41401427, 54.52564119,
        54.2935089 , 52.94297377, 52.32940952, 53.94121223, 53.7744211 ,
        54.22098992, 53.77238061, 53.27141232, 53.47471939, 53.54521102,
        53.35218583, 52.61123855, 53.3820609 , 52.56605542, 52.15291142,
        52.76868486, 52.52090812, 53.0514135 , 51.85027676, 53.37507535,
        52.91363527, 52.35392996, 53.53326564, 52.5241777 , 54.25676981,
        53.23982845, 53.07297985, 52.43911516, 53.47421627, 52.97220184]),
 array([54.55056593, 54.62248872, 53.08467844, 52.47453128, 54.53238494,
        54.29816736, 52.96785951, 52.42098227, 53.97005335, 53.78886659,
        54.23487718, 53.78653576, 53.27914384, 53.53475593, 53.56055664,
        53.40425541, 52.63141786, 53.39544117, 52.61794066, 52.16790905,
        52.83535488, 52.67956959, 53.15464155, 51.91718088, 53.44317397,
        52.96386112, 52.42866433, 53.57008133, 52.57750135, 54.26820989,
        53.33111032, 53.11731003, 52.46342163, 53.51391124, 52.996171  ]))

In [11]:
out1[1] == out2[1], out1[2] == out2[2]

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True]),
 array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True]))

#### And you do!
```


```

### Our epeakRest errors are NOT symmetric. So if we only pass the lower error, we do not expect to get the same as had we passed both the lower and upper errors.

In [12]:
param = 'epeakRest'
out1 = to_log(  x = df[param], 
               xerr=[df[param+'_err_low'], 
                     df[param+'_err_up']], 
               which='both', 
               errTypeReturn='ci'
            )

out1

You have Margins of Error

(array([3.43646946, 3.50643145, 3.04247935, 3.59167519, 3.45950575,
        2.97325762, 2.86648647, 2.33270509, 2.88375434, 2.99229292,
        3.16820682, 3.05053867, 2.55857095, 2.85059   , 2.457404  ,
        2.79032391, 2.40343558, 2.43401211, 2.27210394, 1.74770618,
        2.3255078 , 2.53830136, 2.42366128, 2.38899218, 2.43898041,
        2.11096192, 1.78440188, 2.74683131, 2.08541495, 3.46699154,
        2.94254254, 2.32751543, 2.06024854, 2.66904495, 2.30113692]),
 array([3.40623056, 3.47220877, 3.00554282, 3.5152741 , 3.45160669,
        2.96753394, 2.8393939 , 2.25201827, 2.86931098, 2.96782596,
        3.15276556, 3.02757416, 2.55182023, 2.78560252, 2.45069745,
        2.76245284, 2.39265631, 2.42497384, 2.25419078, 1.72281051,
        2.27674394, 2.4910289 , 2.36810024, 2.36968447, 2.3244098 ,
        2.05708898, 1.73906419, 2.72953174, 2.00323809, 3.45502346,
        2.86667924, 2.2821817 , 2.04545511, 2.64461539, 2.28408755]),
 array([3.46473926, 3.53815323, 3.07651921, 3.6566252 , 3.46726371,
        2.97890684, 2.89198771, 2.4007241 , 2.89773277, 3.01545468,
        3.18311787, 3.07234961, 2.56521834, 2.9167639 , 2.46449556,
        2.82036227, 2.41356905, 2.4431272 , 2.28947212, 1.77189853,
        2.36724987, 2.6025637 , 2.48289077, 2.40858534, 2.50304234,
        2.18458231, 1.82208289, 2.76511032, 2.15033597, 3.47895066,
        3.03312085, 2.36309033, 2.07528325, 2.69244653, 2.31793613]))

In [13]:
param = 'epeakRest'
out2 = to_log(  x = df[param], 
               xerr=df[param+'_err_low'], 
               which='both', 
               errTypeReturn='ci'
            )

out2

(array([3.43646946, 3.50643145, 3.04247935, 3.59167519, 3.45950575,
        2.97325762, 2.86648647, 2.33270509, 2.88375434, 2.99229292,
        3.16820682, 3.05053867, 2.55857095, 2.85059   , 2.457404  ,
        2.79032391, 2.40343558, 2.43401211, 2.27210394, 1.74770618,
        2.3255078 , 2.53830136, 2.42366128, 2.38899218, 2.43898041,
        2.11096192, 1.78440188, 2.74683131, 2.08541495, 3.46699154,
        2.94254254, 2.32751543, 2.06024854, 2.66904495, 2.30113692]),
 array([3.40623056, 3.47220877, 3.00554282, 3.5152741 , 3.45160669,
        2.96753394, 2.8393939 , 2.25201827, 2.86931098, 2.96782596,
        3.15276556, 3.02757416, 2.55182023, 2.78560252, 2.45069745,
        2.76245284, 2.39265631, 2.42497384, 2.25419078, 1.72281051,
        2.27674394, 2.4910289 , 2.36810024, 2.36968447, 2.3244098 ,
        2.05708898, 1.73906419, 2.72953174, 2.00323809, 3.45502346,
        2.86667924, 2.2821817 , 2.04545511, 2.64461539, 2.28408755]),
 array([3.46473926, 3.53815323, 3.07651921, 3.6566252 , 3.46726371,
        2.97890684, 2.89198771, 2.4007241 , 2.89773277, 3.01545468,
        3.18311787, 3.07234961, 2.56521834, 2.90710663, 2.46400855,
        2.8165137 , 2.41395378, 2.44286612, 2.28930742, 1.77125178,
        2.36934485, 2.58092964, 2.47291364, 2.40747792, 2.52954862,
        2.15888354, 1.8254508 , 2.76346808, 2.15448889, 3.47863864,
        3.00710375, 2.36856109, 2.07455462, 2.69217319, 2.31754218]))

In [14]:
out1[1] == out2[1], out1[2] == out2[2]

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True]),
 array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False]))